name: "Security Pipeline (SAST & SCA)"
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  security-events: write
  contents: read
 
jobs:
  sast-semgrep:
    name: SAST Scan (Semgrep)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          semgrep scan --config "p/python" --config "p/flask" --config "p/security-audit" --sarif --output semgrep.sarif
      - name: Upload Semgrep results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
 
  sca-snyk:
    name: SCA Scan (Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install Snyk CLI
        run: npm install -g snyk
 
      - name: Run Snyk Test
        # LE SECRET : --command=skip force snyk Ã  ne pas essayer d'installer les deps
        # On utilise le nom SNYK_TOKEN (vÃ©rifie bien le N dans tes secrets GitHub)
        run: |
          snyk test --token=${{ secrets.SNYK_TOKEN }} \
                    --file=requirements.txt \
                    --command=skip \
                    --sarif-file-output=snyk.sarif || true
 
      - name: Upload Snyk results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
        if: always()
 
  reporting:
    name: Final Report
    needs: [sast-semgrep, sca-snyk]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "### ðŸš€ Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "VÃ©rifiez l'onglet **Security > Code scanning**." >> $GITHUB_STEP_SUMMARY